version: "3.8"

services:
    react:
        build:
            context: .
            dockerfile: Dockerfile-react
        ports:
            - "3000:80"
        restart: unless-stopped

volumes:
    react_build:
